
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 06 18:58:29 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 20;
  public static final int EGAL = 8;
  public static final int CSTENTIERE = 21;
  public static final int PARENTHESEOUVRANTE = 10;
  public static final int PLUS = 12;
  public static final int LIRE = 6;
  public static final int INFERIEUR = 24;
  public static final int ECRIRE = 5;
  public static final int FOIS = 14;
  public static final int ALORS = 17;
  public static final int SUPERIEUR = 23;
  public static final int DOUBLEEGAL = 9;
  public static final int MOINS = 13;
  public static final int POINTVIRGULE = 7;
  public static final int SINON = 19;
  public static final int PARENTHESEFERMANTE = 11;
  public static final int ENTIER = 22;
  public static final int EOF = 0;
  public static final int SI = 16;
  public static final int DIVISE = 15;
  public static final int error = 1;
  public static final int DEBUT = 3;
  public static final int FINSI = 18;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

